# Site settings
title: Buoy
tagline: A community-based crisis response system. Because friends don&rsquo;t let friends call the cops.
description: > # this means to ignore newlines until "baseurl:"
  Buoy is a community-based crisis response system.
baseurl: "/buoy"
url: "https://betterangels.github.io" # the base hostname & protocol for your site

# Project-specific settings.
github_repo: "betterangels/buoy"

# Build settings
markdown: kramdown

exclude: [vendor]

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
